# Install script for directory: /Users/ragrawal/random/opencv/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/Users/ragrawal/random/opencv/build_wasm/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/core/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cudev/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/dnn/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/features2d/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/flann/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/highgui/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/java/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/js/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/ml/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/photo/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/python/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/shape/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/stitching/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/superres/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/ts/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/video/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/videoio/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/videostab/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/viz/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/world/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/aruco/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/ccalib/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/cvv/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/datasets/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/dpm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/face/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/freetype/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/hdf/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/hfs/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/img_hash/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/matlab/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/optflow/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/ovis/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/plot/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/reg/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/rgbd/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/saliency/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/sfm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/stereo/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/structured_light/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/text/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/tracking/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/.firstpass/xphoto/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/core/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/flann/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/imgproc/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/java_bindings_generator/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/ml/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/objdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/phase_unwrapping/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/photo/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/plot/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/reg/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/surface_matching/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/video/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/xphoto/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/bioinspired/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/dnn/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/dnn_objdetect/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/dpm/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/face/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/features2d/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/fuzzy/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/hfs/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/img_hash/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/js/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/line_descriptor/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/saliency/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/text/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/tracking/cmake_install.cmake")
  include("/Users/ragrawal/random/opencv/build_wasm/modules/python_bindings_generator/cmake_install.cmake")

endif()

